export type Locale = "en" | "si" | "ta" | "ko";

export const locales: { code: Locale; label: string; native: string }[] = [
  { code: "en", label: "English", native: "EN" },
  { code: "si", label: "Sinhala", native: "සිං" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "ko", label: "Korean", native: "한국어" },
];

export const copy = {
  en: {
    nav: {
      home: "Home",
      about: "About us",
      koica: "KOICA",
      projects: "Our projects",
      dissemination: "Knowledge Dissemination",
      gallery: "Gallery",
      contact: "Contact",
    },
    common: {
      siteTitle: "AKOFE Sri Lanka | Growing brighter, together",
      skipToContent: "Skip to content",
      language: "Language",
      mainNavigation: "Main navigation",
      menu: "Open menu",
      close: "Close menu",
      getInvolved: "Get involved",
      learnMore: "Learn more",
      explore: "Explore our work",
      viewProjects: "View all projects",
      readStory: "Read our story",
      visit: "Visit us",
      email: "Email us",
      call: "Call us",
      footerNote: "Rooted in community. Growing with possibility.",
      footerDescription: "The Association of KOICA Fellows in Sri Lanka (AKOFE) is a dynamic network of Sri Lankan professionals who have participated in training, research, and academic programs sponsored by the Korea International Cooperation Agency (KOICA).",
      footerLine: "A future where every community can thrive.",
      footerExplore: "Explore",
      footerPartners: "Partners",
      footerFollow: "Follow AKOFE",
      rights: "© 2025 AKOFE Sri Lanka. All rights reserved.",
      backToTop: "Back to top",
    },
    home: {
      eyebrow: "AKOFE – SRI LANKA",
      title: "AKOFE",
      highlight: "",
      lead: "The Association of KOICA Fellows in Sri Lanka (AKOFE) is a dynamic network of Sri Lankan professionals who have participated in training, research, and academic programs sponsored by the Korea International Cooperation Agency (KOICA).",
      primary: "Discover our work",
      secondary: "Who we are",
      scroll: "Scroll to explore",
      photoNoteLineOne: "People first.",
      photoNoteLineTwo: "Progress together.",
      stampTop: "ROOTED IN",
      stampWord: "community",
      stampBottom: "GROWING TOGETHER",
      sectionAside: "A BETTER WAY\nFORWARD, TOGETHER",
      heroImageAlt: "People working together outdoors",
      slidesLabel: "Hero presentation",
      carouselDescription: "carousel",
      slideDescription: "slide",
      slideOf: "of",
      slideLabels: ["Community in focus", "People working together", "A place to grow", "Growing together", "A brighter future"],
      previousSlide: "Previous slide",
      nextSlide: "Next slide",
      statOne: "Years of service",
      statTwo: "Members",
      statThree: "Projects",
      introEyebrow: "ABOUT AKOFE",
      introTitle: "Association of KOICA Fellows in Sri Lanka (AKOFE)",
      introBody: "AKOFE is a voluntary network bringing together Sri Lankan professionals who have taken part in KOICA-sponsored training, research, and academic programs. We strengthen alumni connections and promote knowledge-sharing and cooperation between Sri Lanka and Korea through professional, community, and development initiatives.",
      sdgTitle: "Contributing to the Sustainable Development Goals",
      sdgNote: "AKOFE’s activities align with these goals through learning, professional networks, community initiatives, and international cooperation.",
      sdgGoals: [
        ["04", "Quality Education", "Sharing knowledge and supporting lifelong learning."],
        ["08", "Decent Work and Economic Growth", "Connecting professionals and strengthening skills."],
        ["09", "Industry, Innovation and Infrastructure", "Sharing expertise, technology, and practical ideas."],
        ["17", "Partnerships for the Goals", "Building cooperation between Sri Lanka and Korea."],
      ],
      workEyebrow: "Where we focus",
      workTitle: "Small steps. Lasting change.",
      workBody: "From learning and livelihoods to healthier, more resilient communities, our work starts with local priorities.",
      projectTitle: "Good things grow when we work together.",
      projectBody: "Meet the projects shaped by community voices and strengthened through partnership.",
      closingTitle: "A brighter future starts with a conversation.",
      closingBody: "Have an idea, a question or a way to work together? We’d love to hear from you.",
      pillars: [
        ["01", "Learning for life", "Opening doors to knowledge, skills and confidence at every age."],
        ["02", "Stronger livelihoods", "Supporting people to build secure, hopeful futures for their families."],
        ["03", "Thriving communities", "Growing the connections and local action that help everyone belong."],
      ],
    },
    about: {
      eyebrow: "OUR STORY",
      title: "AKOFE-Sri Lanka",
      heroTagline: "Driven by 900+ Members, Connected Across the Island",
      highlight: "",
      lead: "The Association of KOICA Fellows in Sri Lanka (AKOFE) is a voluntary organization connecting Sri Lankan professionals who have taken part in Korea International Cooperation Agency (KOICA) training, research, and academic programmes.",
      imageAlt: "KOICA alumni meeting and sharing ideas",
      introTitle: "A network built through learning and service.",
      introBody: "Founded in 1999, AKOFE brings together senior public servants and former officials who received Korean Government scholarships for training in South Korea. More than 900 members share knowledge through seminars, community development initiatives, and professional events across education, health, environment, governance, and other sectors.",
      missionLabel: "Our community",
      missionTitle: "Strengthening Sri Lanka–Korea ties.",
      missionBody: "AKOFE works with KOICA and other partners to bring Korean expertise, technology, and experience to local institutions and communities, supporting national development and people in need.",
      valuesTitle: "Turning shared learning into action.",
      values: [
        ["Knowledge exchange", "Seminars and learning programmes help alumni share expertise and practical ideas."],
        ["Community development", "Member initiatives bring skills and experience to local priorities and underserved communities."],
        ["Professional networks", "Events connect fellows across professions and create space for collaboration."],
        ["Sri Lanka–Korea cooperation", "AKOFE works with KOICA and partners to share Korean expertise, technology, and experience."],
      ],
      presidentTitle: "A message from the President.",
      executiveTitle: "Executive Members",
      presidentMessage: "I warmly welcome you to learn about AKOFE and the work of our alumni. Members apply what they have learned through KOICA programmes in their own fields, guided by innovation, service, and collaboration. I am grateful to KOICA, our dedicated members, and our partners for their support. Together, we will continue turning shared knowledge into action for Sri Lanka and strengthening the friendship between our two countries.",
      presidentName: "Roshan Serasinghe",
      presidentRole: "President, Association of KOICA Fellows in Sri Lanka",
      closingTitle: "Let’s make something meaningful happen.",
      closingBody: "Good partnerships begin with a hello. Tell us what matters to you.",
    },
    koica: {
      eyebrow: "PARTNERS IN PROGRESS",
      title: "Working together",
      highlight: "for lasting change.",
      lead: "AKOFE and KOICA share a belief in partnership, people and practical progress for communities in Sri Lanka.",
      imageAlt: "Partners working together around a table",
      introTitle: "A partnership with purpose.",
      introBody: "The Korea International Cooperation Agency (KOICA) works around the world to support sustainable development. Our KOICA page celebrates the spirit of international cooperation and the shared work that helps communities build opportunity.",
      noteTitle: "Local voices. Shared ambition.",
      noteBody: "International cooperation is strongest when local knowledge leads. We value the ideas, relationships and shared learning that make partnership meaningful.",
      focusTitle: "What partnership makes possible.",
      focus: [
        ["01", "Shared learning", "Bringing experience and ideas together across communities and cultures."],
        ["02", "Stronger connections", "Creating space for local organizations and international partners to work side by side."],
        ["03", "Sustainable progress", "Keeping community priorities at the heart of long-term development."],
      ],
      quote: "“Development works best when people are partners in shaping their own future.”",
      quoteBy: "The spirit of cooperation",
      closingTitle: "Interested in working together?",
      closingBody: "We welcome conversations with organizations that share our commitment to people-led progress.",
      overviewTitle: "KOICA in Sri Lanka",
      overviewBody: "The Korea International Cooperation Agency (KOICA) works with partner countries to support sustainable development. In Sri Lanka, KOICA connects Korea’s development cooperation with local institutions and communities. Its CIAT Fellowship Programme brings public-sector officials to Korea to build knowledge and skills they can apply in their work.",
      officialLinksLabel: "KOICA official resources",
      globalLinkLabel: "KOICA global website",
      missionLinkLabel: "Mission and vision",
      officeLinkLabel: "KOICA Sri Lanka Office website",
      directorSectionTitle: "A message from the Country Director",
      directorMessage: "The KOICA CIAT Fellowship Programme is one of Korea’s flagship initiatives for human resource development, inviting public-sector officials from partner countries to Korea to strengthen their knowledge and skills across diverse sectors. KOICA takes great pride in alumni who continue to contribute to national development. I sincerely appreciate AKOFE’s enduring commitment to strengthening the alumni network. Your dedication deepens collaboration and the enduring friendship between Korea and Sri Lanka. You are true bridges of friendship between our two nations. I wish AKOFE continued success and prosperity.",
      directorName: "Lee YooLi",
      directorRole: "Country Director, KOICA Sri Lanka Office",
      directorImageAlt: "Lee YooLi, Country Director of the KOICA Sri Lanka Office",
      videoTitle: "KOICA in action",
      videoDescription: "Watch the video to learn more about KOICA’s cooperation and fellowship work.",
      videoFrameTitle: "KOICA video",
    },
    projects: {
      eyebrow: "OUR WORK IN ACTION",
      title: "Empowering Communities, Sustaining Futures.",
      highlight: "",
      lead: "AKOFE translates Korean learning into local action through targeted educational, social, and sustainable development initiatives across the island.",
      imageAlt: "A group sharing ideas at a workshop",
      introTitle: "AKOFE projects in action.",
      introBody: "Browse projects by year, district, and SDG goal, then open a project to explore its story and photos.",
      projectsTitle: "A few of the ways we work.",
      projects: [
        ["Learning & skills", "Creating welcoming ways for people to learn, share skills and build confidence for what comes next.", "EDUCATION"],
        ["Community wellbeing", "Supporting the connections, care and local initiatives that help people and families flourish.", "WELLBEING"],
        ["Sustainable futures", "Working with communities to nurture resilient livelihoods and a healthy environment.", "SUSTAINABILITY"],
        ["Partnership & exchange", "Bringing local groups and partners together to share knowledge and make good ideas go further.", "PARTNERSHIP"],
      ],
      statusNote: "Project details are being updated. Get in touch to learn more about our current work.",
      closingTitle: "Have a project idea?",
      closingBody: "We’re always glad to meet people who care about their community.",
    },
    dissemination: {
      title: "Knowledge Dissemination",
      lead: "AKOFE shares practical and innovative skills with students, teachers and professionals across Sri Lanka through hands-on training, lectures and donation programs.",
      programsLabel: "PROGRAM",
      photosLabel: "Photo Highlights of the Event",
      topic: "Lecture Topic",
      person: "Resource Person",
      closingTitle: "Want to host a program?",
      closingBody: "Reach out to bring an AKOFE knowledge dissemination session to your school, institute or organization.",
    },
    gallery: {
      eyebrow: "MOMENTS & MILESTONES",
      title: "A Thousand Words in Every Frame.",
      highlight: "",
      lead: "See our mission in motion. From capacity-building workshops to grassroots volunteer initiatives, these pictures capture the real stories of progress driven by AKOFE across the island.",
      momentsLabel: "MOMENTS",
      note: "Photographs shown here are selected from AKOFE's documented project activities.",
      closingTitle: "Have a moment to share?",
      closingBody: "We’d love to celebrate the people and stories that make your community special.",
    },
    contact: {
      eyebrow: "LET’S TALK",
      title: "We’re Here to Connect.",
      highlight: "",
      lead: "Have inquiries or ideas for collaboration? Contact the Association of KOICA Fellows in Sri Lanka (AKOFE) and let’s discuss how we can drive sustainable development together.",
      introTitle: "We’d love to hear from you.",
      introBody: "Reach out to learn more about AKOFE, our work or ways we might work together. Our team will be glad to point you in the right direction.",
      addressLabel: "Find us",
      address: "Sri Lanka",
      emailLabel: "Write to us",
      email: "Official email to be added",
      phoneLabel: "Give us a call",
      phone: "Official phone number to be added",
      formTitle: "Send us a message",
      nameLabel: "Your name",
      namePlaceholder: "How should we address you?",
      emailFieldLabel: "Email address",
      emailPlaceholder: "you@example.com",
      subjectLabel: "I’m getting in touch about",
      subjectOptions: ["A general enquiry", "Partnership", "Our projects", "Volunteering", "Something else"],
      messageLabel: "Your message",
      messagePlaceholder: "Tell us a little about what’s on your mind...",
      send: "Send message",
      formNote: "This preview form is not connected yet. Add an official contact email or form service before accepting messages.",
    },
  },
  si: {
    nav: {
      home: "මුල් පිටුව",
      about: "අප ගැන",
      koica: "KOICA",
      projects: "අපගේ ව්‍යාපෘති",
      dissemination: "දැනුම බෙදාහැරීම",
      gallery: "ගැලරිය",
      contact: "අමතන්න",
    },
    common: {
      siteTitle: "AKOFE ශ්‍රී ලංකා | එකට දීප්තිමත්ව වැඩෙමු",
      skipToContent: "අන්තර්ගතයට යන්න",
      language: "භාෂාව",
      mainNavigation: "ප්‍රධාන මෙනුව",
      menu: "මෙනුව විවෘත කරන්න",
      close: "මෙනුව වසන්න",
      getInvolved: "එක්වන්න",
      learnMore: "තව දැනගන්න",
      explore: "අපගේ වැඩ බලන්න",
      viewProjects: "සියලු ව්‍යාපෘති බලන්න",
      readStory: "අපේ කතාව කියවන්න",
      visit: "අපව හමුවන්න",
      email: "විද්‍යුත් තැපැල් කරන්න",
      call: "අමතන්න",
      footerNote: "ප්‍රජාව සමඟ මුල් බැස, හැකියාවන් සමඟ වැඩෙමු.",
      footerDescription: "ශ්‍රී ලංකාවේ KOICA ආදි ශිෂ්‍ය සංගමය (AKOFE) යනු කොරියානු ජාත්‍යන්තර සහයෝගිතා ඒජන්සිය (KOICA) අනුග්‍රහය දැක්වූ පුහුණු, පර්යේෂණ සහ අධ්‍යයන වැඩසටහන්වලට සහභාගී වූ ශ්‍රී ලාංකික වෘත්තිකයන්ගේ ජවසම්පන්න ජාලයකි.",
      footerLine: "සෑම ප්‍රජාවකටම දියුණු විය හැකි අනාගතයක්.",
      footerExplore: "ගවේෂණය කරන්න",
      footerPartners: "හවුල්කරුවන්",
      footerFollow: "AKOFE සමඟ එක්වන්න",
      rights: "© 2025 AKOFE ශ්‍රී ලංකා. සියලු හිමිකම් ඇවිරිණි.",
      backToTop: "ඉහළට",
    },
    home: {
      eyebrow: "AKOFE – SRI LANKA",
      title: "AKOFE...",
      highlight: "",
      lead: "ශ්‍රී ලංකාවේ KOICA ආදි ශිෂ්‍ය සංගමය (AKOFE) යනු කොරියානු ජාත්‍යන්තර සහයෝගිතා ඒජන්සිය (KOICA) අනුග්‍රහය දැක්වූ පුහුණු, පර්යේෂණ සහ අධ්‍යයන වැඩසටහන්වලට සහභාගී වූ ශ්‍රී ලාංකික වෘත්තිකයන්ගේ ජවසම්පන්න ජාලයකි.",
      primary: "අපගේ වැඩ හඳුනාගන්න",
      secondary: "අප කවුරුන්ද",
      scroll: "තවත් බලන්න",
      photoNoteLineOne: "මිනිසුන් ප්‍රථමයෙන්.",
      photoNoteLineTwo: "එකට ප්‍රගතිය.",
      stampTop: "ප්‍රජාව තුළ",
      stampWord: "මුල් බැස",
      stampBottom: "එකට වැඩෙමු",
      sectionAside: "වඩා හොඳ මඟක්\nඑකට ඉදිරියට",
      heroImageAlt: "එළිමහනේ එකට වැඩ කරන මිනිසුන්",
      slidesLabel: "ප්‍රධාන ඉදිරිපත් කිරීම",
      carouselDescription: "රූප පෙළ",
      slideDescription: "රූපය",
      slideOf: "න්",
      slideLabels: ["ප්‍රජා අවධානය", "එකට වැඩ කරන මිනිසුන්", "වැඩීමට සුදුසු තැනක්", "එකට වර්ධනය වෙමින්", "දීප්තිමත් අනාගතයක්"],
      previousSlide: "පෙර රූපය",
      nextSlide: "ඊළඟ රූපය",
      statOne: "වසරක සේවය",
      statTwo: "සාමාජිකයන්",
      statThree: "ව්‍යාපෘති",
      introEyebrow: "AKOFE ගැන",
      introTitle: "ශ්‍රී ලංකාවේ KOICA ආදි ශිෂ්‍ය සංගමය (AKOFE)",
      introBody: "KOICA අනුග්‍රහය ලැබූ පුහුණු, පර්යේෂණ සහ අධ්‍යයන වැඩසටහන්වලට සහභාගී වූ ශ්‍රී ලාංකික වෘත්තිකයන් එක් කරන ස්වේච්ඡා ජාලයකි AKOFE. වෘත්තීය, ප්‍රජා සහ සංවර්ධන වැඩසටහන් හරහා ආදි ශිෂ්‍ය සබඳතා ශක්තිමත් කරමින් ශ්‍රී ලංකාව සහ කොරියාව අතර දැනුම බෙදාගැනීම හා සහයෝගිතාව ප්‍රවර්ධනය කරමු.",
      sdgTitle: "තිරසාර සංවර්ධන ඉලක්ක සඳහා දායකත්වය",
      sdgNote: "ඉගෙනීම, වෘත්තීය ජාල, ප්‍රජා මුලපිරීම් සහ ජාත්‍යන්තර සහයෝගිතාව හරහා AKOFE හි ක්‍රියාකාරකම් මෙම ඉලක්ක සමඟ ගැළපේ.",
      sdgGoals: [
        ["04", "ගුණාත්මක අධ්‍යාපනය", "දැනුම බෙදාගැනීම සහ ජීවිත කාලය පුරා ඉගෙනීමට සහාය වීම."],
        ["08", "යහපත් රැකියා සහ ආර්ථික වර්ධනය", "වෘත්තිකයන් සම්බන්ධ කර කුසලතා ශක්තිමත් කිරීම."],
        ["09", "කර්මාන්ත, නවෝත්පාදන සහ යටිතල පහසුකම්", "විශේෂඥ දැනුම, තාක්ෂණය සහ ප්‍රායෝගික අදහස් බෙදාගැනීම."],
        ["17", "ඉලක්ක සඳහා හවුල්කාරිත්වයන්", "ශ්‍රී ලංකාව සහ කොරියාව අතර සහයෝගිතාව ගොඩනැගීම."],
      ],
      workEyebrow: "අපගේ අවධානය",
      workTitle: "කුඩා පියවර. දිගුකාලීන වෙනස.",
      workBody: "අධ්‍යාපනයේ සිට ජීවනෝපායන් දක්වා, අපගේ වැඩ දේශීය ප්‍රමුඛතාවලින් ආරම්භ වේ.",
      projectTitle: "එකට වැඩ කළ විට හොඳ දේ වැඩෙයි.",
      projectBody: "ප්‍රජා හඬින් හැඩගැසී හවුල්කාරිත්වයෙන් ශක්තිමත් වූ ව්‍යාපෘති හඳුනාගන්න.",
      closingTitle: "දීප්තිමත් අනාගතයක් සංවාදයකින් ඇරඹේ.",
      closingBody: "ඔබට අදහසක්, ප්‍රශ්නයක් හෝ එක්ව වැඩ කිරීමට කැමැත්තක් තිබේද? අපට කියන්න.",
      pillars: [
        ["01", "ජීවිතයට ඉගෙනීම", "සෑම වයසකදීම දැනුම, කුසලතා සහ විශ්වාසය සඳහා දොරටු විවෘත කිරීම."],
        ["02", "ශක්තිමත් ජීවනෝපාය", "පවුල් සඳහා සුරක්ෂිත හා බලාපොරොත්තු සහගත අනාගතයක් ගොඩනැගීමට සහාය වීම."],
        ["03", "සමෘද්ධිමත් ප්‍රජාවන්", "සෑම කෙනෙකුටම අයත් බව දැනෙන දේශීය සම්බන්ධතා සහ ක්‍රියාකාරිත්වය වර්ධනය කිරීම."],
      ],
    },
    about: {
      eyebrow: "අපේ කතාව",
      title: "AKOFE-ශ්‍රී ලංකා",
      heroTagline: "සාමාජිකයන් 900+ ක් විසින් මෙහෙයවන, දිවයින පුරා සම්බන්ධ වූ",
      highlight: "",
      lead: "ශ්‍රී ලංකාවේ KOICA සාමාජිකයන්ගේ සංගමය (AKOFE) යනු කොරියානු ජාත්‍යන්තර සහයෝගිතා ඒජන්සියේ (KOICA) පුහුණු, පර්යේෂණ සහ අධ්‍යයන වැඩසටහන්වලට සහභාගී වූ ශ්‍රී ලාංකික වෘත්තිකයන් එක් කරන ස්වේච්ඡා සංවිධානයකි.",
      imageAlt: "KOICA ආදි සිසුන් හමුවී අදහස් බෙදාගනිති",
      introTitle: "ඉගෙනීමෙන් හා සේවයෙන් ගොඩනැගුණු ජාලයක්.",
      introBody: "1999 දී පිහිටුවන ලද AKOFE, දකුණු කොරියාවේ පුහුණුව සඳහා කොරියානු රජයේ ශිෂ්‍යත්ව ලැබූ ජ්‍යෙෂ්ඨ රාජ්‍ය සේවකයන් සහ හිටපු නිලධාරීන් එක් කරයි. සාමාජිකයන් 900කට වැඩි පිරිසක් අධ්‍යාපනය, සෞඛ්‍යය, පරිසරය, පාලනය සහ වෙනත් ක්ෂේත්‍රවල සම්මන්ත්‍රණ, ප්‍රජා සංවර්ධන වැඩසටහන් සහ වෘත්තීය හමුවීම් හරහා දැනුම බෙදාගනිති.",
      missionLabel: "අපගේ ප්‍රජාව",
      missionTitle: "ශ්‍රී ලංකා–කොරියා සබඳතා ශක්තිමත් කිරීම.",
      missionBody: "දේශීය ආයතන හා ප්‍රජාවන්ට කොරියානු විශේෂඥ දැනුම, තාක්ෂණය සහ අත්දැකීම් ලබාදීමටත්, ජාතික සංවර්ධනයට සහ අවශ්‍යතා ඇති ජනතාවට සහාය වීමටත් AKOFE, KOICA සහ හවුල්කරුවන් සමඟ කටයුතු කරයි.",
      valuesTitle: "හවුල් ඉගෙනීම ක්‍රියාවට නැංවීම.",
      values: [
        ["දැනුම හුවමාරුව", "සම්මන්ත්‍රණ සහ ඉගෙනුම් වැඩසටහන් හරහා සාමාජිකයෝ විශේෂඥ දැනුම සහ ප්‍රායෝගික අදහස් බෙදාගනිති."],
        ["ප්‍රජා සංවර්ධනය", "සාමාජික මුලපිරීම් දේශීය අවශ්‍යතා සහ අඩු වරප්‍රසාදිත ප්‍රජාවන්ට දැනුම හා අත්දැකීම් ගෙන යයි."],
        ["වෘත්තීය ජාල", "විවිධ වෘත්තීන්හි සාමාජිකයන් හමුවී සහයෝගීතාවයට අවස්ථා ගොඩනගති."],
        ["ශ්‍රී ලංකා–කොරියා සහයෝගීතාව", "කොරියානු දැනුම, තාක්ෂණය සහ අත්දැකීම් බෙදාගැනීමට AKOFE, KOICA සහ හවුල්කරුවන් සමඟ කටයුතු කරයි."],
      ],
      presidentTitle: "සභාපතිගේ පණිවිඩය.",
      executiveTitle: "විධායක කමිටු සාමාජිකයින්",
      presidentMessage: "AKOFE සහ අපගේ ආදි සිසුන්ගේ කටයුතු පිළිබඳව දැනගැනීමට ඔබ සාදරයෙන් පිළිගනිමි. සාමාජිකයෝ KOICA වැඩසටහන් තුළින් ලැබූ දැනුම නවෝත්පාදනය, සේවය සහ සහයෝගීතාව සමඟ තම ක්ෂේත්‍රවල යොදාගනිති. KOICA, කැපවූ සාමාජිකයන් සහ හවුල්කරුවන්ගේ සහායට මම කෘතඥ වෙමි. අපගේ හවුල් දැනුම ශ්‍රී ලංකාව වෙනුවෙන් ක්‍රියාවට නංවමින් දෙරටේ මිත්‍රත්වය ශක්තිමත් කරමු.",
      presidentName: "රොෂාන් සෙරසිංහ",
      presidentRole: "සභාපති, ශ්‍රී ලංකාවේ KOICA සාමාජිකයන්ගේ සංගමය",
      closingTitle: "අර්ථවත් දෙයක් එක්ව කරමු.",
      closingBody: "හොඳ හවුල්කාරිත්වයක් ආරම්භ වන්නේ ආයුබෝවන් කියාය. ඔබට වැදගත් දේ අපට කියන්න.",
    },
    koica: {
      eyebrow: "ප්‍රගතියේ හවුල්කරුවන්",
      title: "දිගුකාලීන වෙනසක්",
      highlight: "සඳහා එක්ව වැඩ කරමු.",
      lead: "ශ්‍රී ලංකාවේ ප්‍රජාවන් සඳහා හවුල්කාරිත්වය, මිනිසුන් සහ ප්‍රායෝගික ප්‍රගතිය පිළිබඳ විශ්වාසයක් AKOFE සහ KOICA බෙදා ගනී.",
      imageAlt: "මේසයක් වටා එක්ව වැඩ කරන හවුල්කරුවන්",
      introTitle: "අරමුණක් සහිත හවුල්කාරිත්වයක්.",
      introBody: "කොරියානු ජාත්‍යන්තර සහයෝගිතා ඒජන්සිය (KOICA) තිරසාර සංවර්ධනයට සහාය වීම සඳහා ලොව පුරා කටයුතු කරයි. ජාත්‍යන්තර සහයෝගිතාවේ ජීවගුණය සහ ප්‍රජාවන්ට අවස්ථා ගොඩනැගීමට උපකාර වන හවුල් වැඩ අපගේ KOICA පිටුවෙන් සමරමු.",
      noteTitle: "දේශීය හඬ. පොදු අරමුණ.",
      noteBody: "දේශීය දැනුම පෙරමුණ ගන්නා විට ජාත්‍යන්තර සහයෝගිතාව වඩාත් ශක්තිමත් වේ. හවුල්කාරිත්වය අර්ථවත් කරන අදහස්, සබඳතා සහ ඉගෙනීම අපි අගය කරමු.",
      focusTitle: "හවුල්කාරිත්වයෙන් කළ හැකි දේ.",
      focus: [
        ["01", "පොදු ඉගෙනීම", "ප්‍රජාවන් හා සංස්කෘතීන් අතර අත්දැකීම් සහ අදහස් එක් කිරීම."],
        ["02", "ශක්තිමත් සබඳතා", "දේශීය සංවිධාන සහ ජාත්‍යන්තර හවුල්කරුවන් එක්ව වැඩ කිරීමට අවකාශ සැලසීම."],
        ["03", "තිරසාර ප්‍රගතිය", "දිගුකාලීන සංවර්ධනයේදී ප්‍රජා ප්‍රමුඛතා හදවතෙහි තබා ගැනීම."],
      ],
      quote: "“මිනිසුන් තම අනාගතය හැඩගැස්වීමේ හවුල්කරුවන් වන විට සංවර්ධනය සාර්ථක වේ.”",
      quoteBy: "සහයෝගිතාවේ ජීවගුණය",
      closingTitle: "එකට වැඩ කිරීමට කැමතිද?",
      closingBody: "මිනිසුන් මෙහෙයවන ප්‍රගතිය වෙනුවෙන් කැපවූ සංවිධාන සමඟ සංවාදයට අපි සූදානම්.",
      overviewTitle: "ශ්‍රී ලංකාවේ KOICA",
      overviewBody: "කොරියානු ජාත්‍යන්තර සහයෝගිතා ඒජන්සිය (KOICA) තිරසාර සංවර්ධනයට සහාය වීමට හවුල්කාර රටවල් සමඟ කටයුතු කරයි. ශ්‍රී ලංකාවේදී, KOICA දේශීය ආයතන හා ප්‍රජාවන් සමඟ සහයෝගයෙන් කටයුතු කරයි. එහි CIAT සාමාජිකත්ව වැඩසටහන රාජ්‍ය අංශයේ නිලධාරීන්ට කොරියාවේදී දැනුම හා කුසලතා වර්ධනය කර ගැනීමට අවස්ථාව ලබා දෙයි.",
      officialLinksLabel: "KOICA නිල සම්පත්",
      globalLinkLabel: "KOICA ගෝලීය වෙබ් අඩවිය",
      missionLinkLabel: "මෙහෙවර සහ දැක්ම",
      officeLinkLabel: "KOICA ශ්‍රී ලංකා කාර්යාලයේ වෙබ් අඩවිය",
      directorSectionTitle: "රටේ අධ්‍යක්ෂවරයාගේ පණිවිඩය",
      directorMessage: "KOICA CIAT සාමාජිකත්ව වැඩසටහන යනු විවිධ ක්ෂේත්‍රයන්හි දැනුම හා කුසලතා වර්ධනය කිරීම සඳහා හවුල්කාර රටවල රාජ්‍ය අංශයේ නිලධාරීන්ට කොරියාවේ පුහුණුව ලබා දෙන කොරියාවේ ප්‍රමුඛ මානව සම්පත් සංවර්ධන වැඩසටහනකි. ජාතික සංවර්ධනයට අඛණ්ඩව දායක වන ආදි සිසුන් පිළිබඳව KOICA ආඩම්බර වේ. ආදි සිසුන්ගේ ජාලය ශක්තිමත් කිරීමට AKOFE දක්වන කැපවීමට මම අවංකව ස්තුති කරමි. ඔබගේ කැපවීම සහයෝගීතාවය හා කොරියාව සහ ශ්‍රී ලංකාව අතර දිගුකාලීන මිත්‍රත්වය තවදුරටත් ශක්තිමත් කරයි. ඔබ දෙරට අතර මිත්‍රත්වයේ සැබෑ පාලම් වේ. AKOFE වෙත අඛණ්ඩ සාර්ථකත්වය සහ සමෘද්ධිය ප්‍රාර්ථනා කරමි.",
      directorName: "Lee YooLi",
      directorRole: "රටේ අධ්‍යක්ෂ, KOICA ශ්‍රී ලංකා කාර්යාලය",
      directorImageAlt: "KOICA ශ්‍රී ලංකා කාර්යාලයේ රටේ අධ්‍යක්ෂ Lee YooLi",
      videoTitle: "ක්‍රියාවෙන් KOICA",
      videoDescription: "KOICA හි සහයෝගිතා සහ සාමාජිකත්ව වැඩසටහන් පිළිබඳ වැඩිදුර දැනගැනීමට වීඩියෝව නරඹන්න.",
      videoFrameTitle: "KOICA වීඩියෝව",
    },
    projects: {
      eyebrow: "ක්‍රියාවෙන් අපගේ වැඩ",
      title: "ප්‍රජාවන් සවිබල ගන්වමු, අනාගතය තිරසාර කරමු.",
      highlight: "",
      lead: "කොරියානු ඉගෙනීම දිවයින පුරා ඉලක්කගත අධ්‍යාපනික, සමාජීය සහ තිරසාර සංවර්ධන ක්‍රියාකාරකම් හරහා දේශීය ක්‍රියාමාර්ග බවට AKOFE පරිවර්තනය කරයි.",
      imageAlt: "වැඩමුළුවක අදහස් බෙදාගන්නා පිරිසක්",
      introTitle: "AKOFE ව්‍යාපෘති ක්‍රියාවෙන්.",
      introBody: "වසර, දිස්ත්‍රික්කය සහ තිරසාර සංවර්ධන ඉලක්කය අනුව ව්‍යාපෘති පිරික්සා, ඒවායේ විස්තර සහ ඡායාරූප බලන්න.",
      projectsTitle: "අප වැඩ කරන ක්‍රම කිහිපයක්.",
      projects: [
        ["ඉගෙනීම සහ කුසලතා", "ඉගෙනීමට, කුසලතා බෙදා ගැනීමට සහ ඉදිරි ගමනට විශ්වාසය ගොඩනැගීමට අවස්ථා නිර්මාණය කිරීම.", "අධ්‍යාපනය"],
        ["ප්‍රජා යහපැවැත්ම", "මිනිසුන්ට සහ පවුල්වලට සමෘද්ධිමත් වීමට උපකාර වන සබඳතා හා දේශීය මුලපිරීම්වලට සහාය වීම.", "යහපැවැත්ම"],
        ["තිරසාර අනාගතය", "ප්‍රජාවන් සමඟ එක්ව ඔරොත්තු දෙන ජීවනෝපාය සහ සෞඛ්‍ය සම්පන්න පරිසරයක් පෝෂණය කිරීම.", "තිරසාරත්වය"],
        ["හවුල්කාරිත්වය සහ හුවමාරුව", "දැනුම බෙදා ගැනීමට සහ හොඳ අදහස් දුර ගෙන යාමට දේශීය කණ්ඩායම් හා හවුල්කරුවන් එක් කිරීම.", "හවුල්කාරිත්වය"],
      ],
      statusNote: "ව්‍යාපෘති තොරතුරු යාවත්කාලීන වෙමින් පවතී. අපගේ වත්මන් වැඩ ගැන දැනගැනීමට අප අමතන්න.",
      closingTitle: "ව්‍යාපෘති අදහසක් තිබේද?",
      closingBody: "තම ප්‍රජාව ගැන සැලකිලිමත් වන මිනිසුන් හමුවීමට අපි කැමතියි.",
    },
    dissemination: {
      title: "දැනුම බෙදාහැරීම",
      lead: "AKOFE ප්‍රායෝගික පුහුණු, දේශන සහ පරිත්‍යාග වැඩසටහන් හරහා ශ්‍රී ලංකාව පුරා සිසුන්, ගුරුවරුන් සහ වෘත්තිකයන් සමඟ ප්‍රායෝගික හා නවීන කුසලතා බෙදා ගනී.",
      programsLabel: "වැඩසටහන",
      photosLabel: "සිදුවීමේ ඡායාරූප",
      topic: "දේශන මාතෘකාව",
      person: "දේශකයා",
      closingTitle: "වැඩසටහනක් පැවැත්වීමට කැමතිද?",
      closingBody: "ඔබේ පාසල, ආයතනය හෝ සංවිධානය වෙත AKOFE දැනුම බෙදාහැරීමේ වැඩසටහනක් ගෙන්වා ගැනීමට අප හා සම්බන්ධ වන්න.",
    },
    gallery: {
      eyebrow: "මතක සහ සන්ධිස්ථාන",
      title: "සෑම රූපරාමුවකම වචන දහසක්.",
      highlight: "",
      lead: "අපගේ මෙහෙවර ක්‍රියාත්මකව බලන්න. ධාරිතා සංවර්ධන වැඩමුළු සිට ප්‍රජා ස්වේච්ඡා ක්‍රියාකාරකම් දක්වා, දිවයින පුරා AKOFE මගින් මෙහෙයවන ප්‍රගතියේ සැබෑ කතා මෙම ඡායාරූපවල සටහන් වේ.",
      momentsLabel: "මොහොත",
      note: "මෙහි දැක්වෙන ඡායාරූප AKOFE විසින් වාර්තා කරන ලද ව්‍යාපෘති ක්‍රියාකාරකම්වලින් තෝරාගෙන ඇත.",
      closingTitle: "බෙදාගැනීමට මොහොතක් තිබේද?",
      closingBody: "ඔබේ ප්‍රජාව විශේෂ කරන මිනිසුන් සහ කතා සමරන්න අපි කැමතියි.",
    },
    contact: {
      eyebrow: "කතා කරමු",
      title: "සම්බන්ධ වීමට අපි මෙහි සිටිමු.",
      highlight: "",
      lead: "විමසීම් හෝ සහයෝගීතා අදහස් තිබේද? ශ්‍රී ලංකාවේ කොයිකා ශිෂ්‍යත්ව ලාභීන්ගේ සංගමය (AKOFE) අමතන්න; තිරසාර සංවර්ධනය එක්ව ඉදිරියට ගෙන යා හැකි ආකාරය සාකච්ඡා කරමු.",
      introTitle: "ඔබෙන් අසන්න අපි කැමතියි.",
      introBody: "AKOFE, අපගේ වැඩ හෝ එක්ව වැඩ කළ හැකි ආකාර ගැන දැනගැනීමට අප අමතන්න. ඔබට මඟ පෙන්වීමට අපගේ කණ්ඩායම සතුටු වේ.",
      addressLabel: "අපව හමුවන්න",
      address: "ශ්‍රී ලංකාව",
      emailLabel: "අපට ලියන්න",
      email: "නිල විද්‍යුත් තැපෑල එක් කළ යුතුය",
      phoneLabel: "අමතන්න",
      phone: "නිල දුරකථන අංකය එක් කළ යුතුය",
      formTitle: "පණිවිඩයක් එවන්න",
      nameLabel: "ඔබේ නම",
      namePlaceholder: "ඔබව අමතන්නේ කෙසේද?",
      emailFieldLabel: "විද්‍යුත් තැපැල් ලිපිනය",
      emailPlaceholder: "you@example.com",
      subjectLabel: "මා සම්බන්ධ වන්නේ",
      subjectOptions: ["සාමාන්‍ය විමසීමක්", "හවුල්කාරිත්වය", "අපගේ ව්‍යාපෘති", "ස්වේච්ඡා සේවය", "වෙනත් කරුණක්"],
      messageLabel: "ඔබේ පණිවිඩය",
      messagePlaceholder: "ඔබ සිතන දේ ගැන ටිකක් කියන්න...",
      send: "පණිවිඩය යවන්න",
      formNote: "මෙය පෙරදසුන් පෝරමයකි. පණිවිඩ භාර ගැනීමට පෙර නිල විද්‍යුත් තැපෑලක් හෝ පෝරම සේවාවක් එක් කරන්න.",
    },
  },
  ta: {
    nav: {
      home: "முகப்பு",
      about: "எங்களைப் பற்றி",
      koica: "KOICA",
      projects: "எங்கள் திட்டங்கள்",
      dissemination: "அறிவுப் பகிர்வு",
      gallery: "படத்தொகுப்பு",
      contact: "தொடர்பு",
    },
    common: {
      siteTitle: "AKOFE இலங்கை | ஒன்றிணைந்து ஒளிமயமாக வளர்வோம்",
      skipToContent: "உள்ளடக்கத்திற்குச் செல்லுங்கள்",
      language: "மொழி",
      mainNavigation: "முதன்மை வழிசெலுத்தல்",
      menu: "பட்டியலைத் திறக்கவும்",
      close: "பட்டியலை மூடவும்",
      getInvolved: "இணைந்துகொள்ளுங்கள்",
      learnMore: "மேலும் அறிக",
      explore: "எங்கள் பணியைப் பாருங்கள்",
      viewProjects: "அனைத்துத் திட்டங்களையும் பாருங்கள்",
      readStory: "எங்கள் கதையைப் படியுங்கள்",
      visit: "எங்களைச் சந்தியுங்கள்",
      email: "மின்னஞ்சல் அனுப்புங்கள்",
      call: "அழையுங்கள்",
      footerNote: "சமூகத்தில் வேரூன்றி, வாய்ப்புகளுடன் வளர்கிறோம்.",
      footerDescription: "இலங்கையின் KOICA முன்னாள் மாணவர் சங்கம் (AKOFE), கொரிய சர்வதேச ஒத்துழைப்பு முகமை (KOICA) ஆதரவளித்த பயிற்சி, ஆராய்ச்சி மற்றும் கல்வித் திட்டங்களில் பங்கேற்ற இலங்கை நிபுணர்களின் துடிப்பான வலையமைப்பாகும்.",
      footerLine: "ஒவ்வொரு சமூகமும் செழிக்கக்கூடிய எதிர்காலம்.",
      footerExplore: "ஆராயுங்கள்",
      footerPartners: "கூட்டாளர்கள்",
      footerFollow: "AKOFE-ஐப் பின்தொடருங்கள்",
      rights: "© 2025 AKOFE இலங்கை. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
      backToTop: "மேலே செல்லுங்கள்",
    },
    home: {
      eyebrow: "AKOFE – SRI LANKA",
      title: "AKOFE",
      highlight: "",
      lead: "இலங்கையின் KOICA முன்னாள் மாணவர் சங்கமான AKOFE, கொரிய சர்வதேச ஒத்துழைப்பு முகமை (KOICA) ஆதரவளித்த பயிற்சி, ஆராய்ச்சி மற்றும் கல்வித் திட்டங்களில் பங்கேற்ற இலங்கை நிபுணர்களின் துடிப்பான வலையமைப்பாகும்.",
      primary: "எங்கள் பணியை அறியுங்கள்",
      secondary: "நாங்கள் யார்",
      scroll: "மேலும் பார்க்கவும்",
      photoNoteLineOne: "மக்களே முதன்மை.",
      photoNoteLineTwo: "ஒன்றாக முன்னேற்றம்.",
      stampTop: "சமூகத்தில்",
      stampWord: "வேரூன்றி",
      stampBottom: "ஒன்றாக வளர்வோம்",
      sectionAside: "சிறந்த வழி\nஒன்றாக முன்னேற",
      heroImageAlt: "வெளியில் ஒன்றாகச் செயல்படும் மக்கள்",
      slidesLabel: "முகப்புப் படத் தொகுப்பு",
      carouselDescription: "படத் தொகுப்பு",
      slideDescription: "படம்",
      slideOf: "இல்",
      slideLabels: ["சமூகத்தின் கவனம்", "ஒன்றாகச் செயல்படும் மக்கள்", "வளர்வதற்கான இடம்", "ஒன்றாக வளர்ந்து", "ஒளிமயமான எதிர்காலம்"],
      previousSlide: "முந்தைய படம்",
      nextSlide: "அடுத்த படம்",
      statOne: "ஆண்டுகால சேவை",
      statTwo: "உறுப்பினர்கள்",
      statThree: "திட்டங்கள்",
      introEyebrow: "AKOFE பற்றி",
      introTitle: "இலங்கையின் KOICA முன்னாள் மாணவர் சங்கம் (AKOFE)",
      introBody: "KOICA ஆதரவளித்த பயிற்சி, ஆராய்ச்சி மற்றும் கல்வித் திட்டங்களில் பங்கேற்ற இலங்கை நிபுணர்களை ஒன்றிணைக்கும் தன்னார்வ வலையமைப்பே AKOFE. தொழில்முறை, சமூக மற்றும் மேம்பாட்டு நடவடிக்கைகள் மூலம் முன்னாள் மாணவர் உறவுகளை வலுப்படுத்தி, இலங்கைக்கும் கொரியாவுக்கும் இடையே அறிவுப் பகிர்வையும் ஒத்துழைப்பையும் ஊக்குவிக்கிறோம்.",
      sdgTitle: "நிலையான வளர்ச்சி இலக்குகளுக்கான பங்களிப்பு",
      sdgNote: "கற்றல், தொழில்முறை வலையமைப்புகள், சமூக முயற்சிகள் மற்றும் சர்வதேச ஒத்துழைப்பு மூலம் AKOFE-இன் செயல்பாடுகள் இந்த இலக்குகளுடன் ஒத்துப்போகின்றன.",
      sdgGoals: [
        ["04", "தரமான கல்வி", "அறிவைப் பகிர்ந்து வாழ்நாள் கற்றலுக்கு ஆதரவளித்தல்."],
        ["08", "கண்ணியமான வேலை மற்றும் பொருளாதார வளர்ச்சி", "நிபுணர்களை இணைத்து திறன்களை வலுப்படுத்துதல்."],
        ["09", "தொழில், புத்தாக்கம் மற்றும் உள்கட்டமைப்பு", "நிபுணத்துவம், தொழில்நுட்பம் மற்றும் நடைமுறை யோசனைகளைப் பகிர்தல்."],
        ["17", "இலக்குகளுக்கான கூட்டாண்மைகள்", "இலங்கைக்கும் கொரியாவுக்கும் இடையிலான ஒத்துழைப்பை உருவாக்குதல்."],
      ],
      workEyebrow: "எங்கள் கவனம்",
      workTitle: "சிறு படிகள். நீடித்த மாற்றம்.",
      workBody: "கல்வி முதல் வாழ்வாதாரம் வரை, எங்கள் பணி உள்ளூர் முன்னுரிமைகளில் தொடங்குகிறது.",
      projectTitle: "ஒன்றாகச் செயல்பட்டால் நல்லவை வளரும்.",
      projectBody: "சமூகக் குரலால் வடிவமைக்கப்பட்டு, கூட்டாண்மையால் வலுப்பெற்ற திட்டங்களைப் பாருங்கள்.",
      closingTitle: "ஒளிமயமான எதிர்காலம் ஒரு உரையாடலில் தொடங்குகிறது.",
      closingBody: "உங்களிடம் யோசனை, கேள்வி அல்லது இணைந்து செயல்பட விருப்பமா? எங்களிடம் கூறுங்கள்.",
      pillars: [
        ["01", "வாழ்நாள் கற்றல்", "அனைத்து வயதினருக்கும் அறிவு, திறன் மற்றும் நம்பிக்கைக்கான கதவுகளைத் திறத்தல்."],
        ["02", "வலுவான வாழ்வாதாரம்", "குடும்பங்களுக்கு பாதுகாப்பான, நம்பிக்கையான எதிர்காலத்தை உருவாக்க உதவுதல்."],
        ["03", "செழிக்கும் சமூகங்கள்", "அனைவருக்கும் உரிமையுணர்வு தரும் உள்ளூர் இணைப்புகளையும் செயலையும் வளர்த்தல்."],
      ],
    },
    about: {
      eyebrow: "எங்கள் கதை",
      title: "AKOFE-இலங்கை",
      heroTagline: "900+ உறுப்பினர்களால் இயக்கப்படும், தீவு முழுவதும் இணைந்த",
      highlight: "",
      lead: "இலங்கையின் KOICA உறுப்பினர்கள் சங்கம் (AKOFE), கொரிய சர்வதேச ஒத்துழைப்பு நிறுவனம் (KOICA) வழங்கிய பயிற்சி, ஆராய்ச்சி, கல்வித் திட்டங்களில் பங்கேற்ற இலங்கை நிபுணர்களை ஒன்றிணைக்கும் தன்னார்வ அமைப்பாகும்.",
      imageAlt: "KOICA பழைய மாணவர்கள் சந்தித்து கருத்துகளைப் பகிர்கிறார்கள்",
      introTitle: "கற்றலாலும் சேவையாலும் உருவான வலையமைப்பு.",
      introBody: "1999-ல் நிறுவப்பட்ட AKOFE, தென் கொரியாவில் பயிற்சி பெற கொரிய அரசின் கல்வி உதவித்தொகை பெற்ற மூத்த அரசுப் பணியாளர்களையும் முன்னாள் அதிகாரிகளையும் இணைக்கிறது. 900-க்கும் மேற்பட்ட உறுப்பினர்கள் கல்வி, சுகாதாரம், சுற்றுச்சூழல், நிர்வாகம் உள்ளிட்ட துறைகளில் கருத்தரங்குகள், சமூக மேம்பாட்டு முயற்சிகள், தொழில்முறை நிகழ்வுகள் வழியாக அறிவைப் பகிர்கின்றனர்.",
      missionLabel: "எங்கள் உறுப்பினர் சமூகம்",
      missionTitle: "இலங்கை–கொரியா உறவை வலுப்படுத்துதல்.",
      missionBody: "உள்ளூர் நிறுவனங்களுக்கும் சமூகங்களுக்கும் கொரிய நிபுணத்துவம், தொழில்நுட்பம், அனுபவத்தை வழங்கவும், தேசிய வளர்ச்சிக்கும் தேவையுள்ள மக்களுக்கும் ஆதரவளிக்கவும் KOICA மற்றும் கூட்டாளர்களுடன் AKOFE செயல்படுகிறது.",
      valuesTitle: "பகிர்ந்த கற்றலைச் செயலாக்குதல்.",
      values: [
        ["அறிவுப் பகிர்வு", "கருத்தரங்குகள் மற்றும் கற்றல் நிகழ்ச்சிகள் மூலம் நிபுணத்துவத்தையும் நடைமுறை யோசனைகளையும் பகிர்கிறோம்."],
        ["சமூக மேம்பாடு", "உறுப்பினர் முயற்சிகள் உள்ளூர் தேவைகளுக்கும் குறைந்த வாய்ப்புள்ள சமூகங்களுக்கும் திறனையும் அனுபவத்தையும் கொண்டு செல்கின்றன."],
        ["தொழில்முறை வலையமைப்புகள்", "நிகழ்வுகள் பல்வேறு துறைகளின் உறுப்பினர்களை இணைத்து ஒத்துழைப்பை வளர்க்கின்றன."],
        ["இலங்கை–கொரியா ஒத்துழைப்பு", "கொரிய நிபுணத்துவம், தொழில்நுட்பம் மற்றும் அனுபவத்தைப் பகிர KOICA மற்றும் கூட்டாளர்களுடன் AKOFE செயல்படுகிறது."],
      ],
      presidentTitle: "தலைவரின் செய்தி.",
      executiveTitle: "நிர்வாகக் குழு உறுப்பினர்கள்",
      presidentMessage: "AKOFE மற்றும் எங்கள் பழைய மாணவர்களின் பணிகளைப் பற்றி அறிய உங்களை அன்புடன் வரவேற்கிறேன். KOICA திட்டங்கள் வழியாகப் பெற்ற கற்றலை உறுப்பினர்கள் தங்கள் துறைகளில் புதுமை, சேவை, ஒத்துழைப்பு ஆகியவற்றுடன் பயன்படுத்துகின்றனர். KOICA, அர்ப்பணிப்புள்ள உறுப்பினர்கள், கூட்டாளர்கள் ஆகியோரின் ஆதரவுக்கு நன்றி. பகிர்ந்த அறிவை இலங்கைக்கான செயலாக மாற்றி இரு நாடுகளின் நட்பை வலுப்படுத்துவோம்.",
      presidentName: "ரோஷன் செரசிங்க",
      presidentRole: "தலைவர், இலங்கையின் KOICA உறுப்பினர்கள் சங்கம்",
      closingTitle: "அர்த்தமுள்ள ஒன்றை உருவாக்குவோம்.",
      closingBody: "நல்ல கூட்டாண்மை ஒரு வணக்கத்தில் தொடங்குகிறது. உங்களுக்கு முக்கியமானதைப் பகிருங்கள்.",
    },
    koica: {
      eyebrow: "முன்னேற்றக் கூட்டாளர்கள்",
      title: "நீடித்த மாற்றத்திற்காக",
      highlight: "ஒன்றாகச் செயல்படுகிறோம்.",
      lead: "இலங்கைச் சமூகங்களுக்கான கூட்டாண்மை, மக்கள், நடைமுறை முன்னேற்றம் ஆகியவற்றில் AKOFE-யும் KOICA-வும் நம்பிக்கை பகிர்கின்றன.",
      imageAlt: "மேசையைச் சுற்றி ஒன்றாகப் பணிபுரியும் கூட்டாளர்கள்",
      introTitle: "நோக்கமுள்ள கூட்டாண்மை.",
      introBody: "கொரிய சர்வதேச ஒத்துழைப்பு நிறுவனம் (KOICA) நிலையான வளர்ச்சிக்கு உலகம் முழுவதும் ஆதரவளிக்கிறது. சர்வதேச ஒத்துழைப்பின் உணர்வையும் சமூகங்கள் வாய்ப்புகளை உருவாக்க உதவும் கூட்டுப் பணியையும் எங்கள் KOICA பக்கம் கொண்டாடுகிறது.",
      noteTitle: "உள்ளூர் குரல்கள். பகிர்ந்த நோக்கம்.",
      noteBody: "உள்ளூர் அறிவு முன்னிலை வகிக்கும்போது சர்வதேச ஒத்துழைப்பு வலுப்பெறுகிறது. கூட்டாண்மையை அர்த்தமுள்ளதாக்கும் யோசனைகள், உறவுகள், பகிர்ந்த கற்றலை மதிக்கிறோம்.",
      focusTitle: "கூட்டாண்மை சாத்தியமாக்குபவை.",
      focus: [
        ["01", "பகிர்ந்த கற்றல்", "சமூகங்கள் மற்றும் பண்பாடுகளிடையே அனுபவங்களையும் யோசனைகளையும் இணைத்தல்."],
        ["02", "வலுவான தொடர்புகள்", "உள்ளூர் அமைப்புகளும் சர்வதேசக் கூட்டாளர்களும் இணைந்து பணியாற்ற இடமளித்தல்."],
        ["03", "நிலையான முன்னேற்றம்", "நீண்டகால வளர்ச்சியில் சமூக முன்னுரிமைகளை மையமாக வைத்தல்."],
      ],
      quote: "“மக்கள் தங்கள் எதிர்காலத்தை வடிவமைக்கும் கூட்டாளர்களாக இருக்கும்போது வளர்ச்சி சிறப்பாக அமையும்.”",
      quoteBy: "ஒத்துழைப்பின் உணர்வு",
      closingTitle: "ஒன்றாகச் செயல்பட விருப்பமா?",
      closingBody: "மக்கள் வழிநடத்தும் முன்னேற்றத்தில் உறுதியாக இருக்கும் அமைப்புகளுடன் உரையாட வரவேற்கிறோம்.",
      overviewTitle: "இலங்கையில் KOICA",
      overviewBody: "கொரிய சர்வதேச ஒத்துழைப்பு நிறுவனம் (KOICA), நிலையான வளர்ச்சியை ஆதரிக்க கூட்டாளர் நாடுகளுடன் செயல்படுகிறது. இலங்கையில், KOICA உள்ளூர் நிறுவனங்கள் மற்றும் சமூகங்களுடன் இணைந்து பணியாற்றுகிறது. அதன் CIAT கல்வி உதவித் திட்டம், அரசுத் துறை அதிகாரிகள் கொரியாவில் அறிவையும் திறன்களையும் வளர்த்துக்கொள்ள வாய்ப்பளிக்கிறது.",
      officialLinksLabel: "KOICA அதிகாரப்பூர்வ வளங்கள்",
      globalLinkLabel: "KOICA உலகளாவிய இணையதளம்",
      missionLinkLabel: "நோக்கமும் தொலைநோக்கும்",
      officeLinkLabel: "KOICA இலங்கை அலுவலக இணையதளம்",
      directorSectionTitle: "நாட்டுப் பணிப்பாளரின் செய்தி",
      directorMessage: "KOICA CIAT கல்வி உதவித் திட்டம், பல்வேறு துறைகளில் அறிவையும் திறன்களையும் வளர்க்க கூட்டாளர் நாடுகளின் அரசுத் துறை அதிகாரிகளை கொரியாவுக்கு அழைக்கும் மனிதவள மேம்பாட்டுக்கான கொரியாவின் முதன்மை முயற்சிகளில் ஒன்றாகும். தேசிய வளர்ச்சிக்குத் தொடர்ந்து பங்களிக்கும் பழைய மாணவர்களை KOICA பெருமையுடன் பாராட்டுகிறது. பழைய மாணவர் வலையமைப்பை வலுப்படுத்த AKOFE தொடர்ந்து காட்டும் அர்ப்பணிப்புக்கு எனது மனமார்ந்த நன்றியைத் தெரிவித்துக்கொள்கிறேன். உங்கள் அர்ப்பணிப்பு ஒத்துழைப்பையும் கொரியா–இலங்கை நீடித்த நட்பையும் மேலும் ஆழப்படுத்துகிறது. நீங்கள் இரு நாடுகளுக்கிடையிலான நட்பின் உண்மையான பாலங்கள். AKOFE தொடர்ந்து வெற்றியும் செழிப்பும் பெற வாழ்த்துகிறேன்.",
      directorName: "Lee YooLi",
      directorRole: "நாட்டுப் பணிப்பாளர், KOICA இலங்கை அலுவலகம்",
      directorImageAlt: "KOICA இலங்கை அலுவலக நாட்டுப் பணிப்பாளர் Lee YooLi",
      videoTitle: "செயலில் KOICA",
      videoDescription: "KOICA-வின் ஒத்துழைப்பு மற்றும் கல்வி உதவிப் பணிகளைப் பற்றி மேலும் அறிய இந்தக் காணொளியைப் பாருங்கள்.",
      videoFrameTitle: "KOICA காணொளி",
    },
    projects: {
      eyebrow: "செயலில் எங்கள் பணி",
      title: "சமூகங்களை வலுப்படுத்துவோம், எதிர்காலத்தை நிலைநிறுத்துவோம்.",
      highlight: "",
      lead: "கொரியக் கற்றலை, தீவு முழுவதும் இலக்கு நோக்கிய கல்வி, சமூக மற்றும் நிலையான வளர்ச்சி முயற்சிகளின் மூலம் உள்ளூர் செயல்பாடாக AKOFE மாற்றுகிறது.",
      imageAlt: "பயிற்சிப் பட்டறையில் கருத்துகளைப் பகிரும் குழு",
      introTitle: "AKOFE திட்டங்கள் செயல்பாட்டில்.",
      introBody: "ஆண்டு, மாவட்டம் மற்றும் நிலையான வளர்ச்சி இலக்கின் அடிப்படையில் திட்டங்களைப் பார்வையிட்டு, அவற்றின் விவரங்களையும் படங்களையும் காணுங்கள்.",
      projectsTitle: "நாங்கள் செயல்படும் சில வழிகள்.",
      projects: [
        ["கல்வியும் திறன்களும்", "கற்றல், திறன் பகிர்வு, அடுத்த கட்டத்திற்கான நம்பிக்கை உருவாக்கும் வரவேற்கத்தக்க வாய்ப்புகளை உருவாக்குதல்.", "கல்வி"],
        ["சமூக நலன்", "மக்களும் குடும்பங்களும் செழிக்க உதவும் தொடர்புகள், அக்கறை, உள்ளூர் முயற்சிகளுக்கு ஆதரவளித்தல்.", "நலன்"],
        ["நிலையான எதிர்காலம்", "நெகிழ்வான வாழ்வாதாரத்தையும் ஆரோக்கியமான சூழலையும் வளர்க்க சமூகங்களுடன் இணைந்து செயல்படுதல்.", "நிலைத்தன்மை"],
        ["கூட்டாண்மையும் பரிமாற்றமும்", "அறிவைப் பகிர்ந்து நல்ல யோசனைகளை விரிவாக்க உள்ளூர் குழுக்களையும் கூட்டாளர்களையும் இணைத்தல்.", "கூட்டாண்மை"],
      ],
      statusNote: "திட்ட விவரங்கள் புதுப்பிக்கப்பட்டு வருகின்றன. எங்கள் தற்போதைய பணியை அறிய எங்களைத் தொடர்புகொள்ளுங்கள்.",
      closingTitle: "திட்ட யோசனை உள்ளதா?",
      closingBody: "தங்கள் சமூகத்தைப் பற்றி அக்கறை கொண்டவர்களைச் சந்திப்பதில் மகிழ்கிறோம்.",
    },
    dissemination: {
      title: "அறிவுப் பகிர்வு",
      lead: "AKOFE நடைமுறைப் பயிற்சிகள், விரிவுரைகள் மற்றும் நன்கொடைத் திட்டங்கள் மூலம் இலங்கை முழுவதும் மாணவர்கள், ஆசிரியர்கள் மற்றும் தொழில்முறையாளர்களுடன் நடைமுறை மற்றும் புதுமையான திறன்களைப் பகிர்கிறது.",
      programsLabel: "நிகழ்ச்சி",
      photosLabel: "நிகழ்வின் புகைப்படங்கள்",
      topic: "விரிவுரைத் தலைப்பு",
      person: "வளவாளர்",
      closingTitle: "நிகழ்ச்சி நடத்த விரும்புகிறீர்களா?",
      closingBody: "உங்கள் பள்ளி, நிறுவனம் அல்லது அமைப்பிற்கு AKOFE அறிவுப் பகிர்வு அமர்வைக் கொண்டுவர எங்களைத் தொடர்பு கொள்ளுங்கள்.",
    },
    gallery: {
      eyebrow: "தருணங்களும் மைல்கற்களும்",
      title: "ஒவ்வொரு சட்டகத்திலும் ஆயிரம் வார்த்தைகள்.",
      highlight: "",
      lead: "எங்கள் பணியை செயல்பாட்டில் காணுங்கள். திறன் மேம்பாட்டுப் பயிற்சிப் பட்டறைகள் முதல் அடிமட்ட தன்னார்வ முயற்சிகள் வரை, தீவு முழுவதும் AKOFE முன்னெடுக்கும் முன்னேற்றத்தின் உண்மைக் கதைகளை இந்தப் படங்கள் பதிவு செய்கின்றன.",
      momentsLabel: "தருணங்கள்",
      note: "இங்கு காட்டப்படும் புகைப்படங்கள் AKOFE ஆவணப்படுத்திய திட்டச் செயல்பாடுகளிலிருந்து தேர்ந்தெடுக்கப்பட்டவை.",
      closingTitle: "பகிர ஒரு தருணம் உள்ளதா?",
      closingBody: "உங்கள் சமூகத்தைச் சிறப்பாக்கும் மனிதர்களையும் கதைகளையும் கொண்டாட விரும்புகிறோம்.",
    },
    contact: {
      eyebrow: "பேசுவோம்",
      title: "இணைவதற்கு நாங்கள் இங்கே இருக்கிறோம்.",
      highlight: "",
      lead: "விசாரணைகள் அல்லது ஒத்துழைப்பு யோசனைகள் உள்ளதா? இலங்கை கொய்கா உறுப்பினர்கள் சங்கத்தை (AKOFE) தொடர்புகொள்ளுங்கள்; நிலையான வளர்ச்சியை இணைந்து எவ்வாறு முன்னெடுக்கலாம் என்பதைப் பேசுவோம்.",
      introTitle: "உங்களிடமிருந்து கேட்க விரும்புகிறோம்.",
      introBody: "AKOFE, எங்கள் பணி அல்லது இணைந்து செயல்படுவதற்கான வழிகளை அறியத் தொடர்புகொள்ளுங்கள். சரியான வழியைக் காட்ட எங்கள் குழு மகிழும்.",
      addressLabel: "எங்களைக் காணுங்கள்",
      address: "இலங்கை",
      emailLabel: "எழுதுங்கள்",
      email: "அதிகாரப்பூர்வ மின்னஞ்சல் சேர்க்கப்பட வேண்டும்",
      phoneLabel: "அழையுங்கள்",
      phone: "அதிகாரப்பூர்வ தொலைபேசி எண் சேர்க்கப்பட வேண்டும்",
      formTitle: "எங்களுக்கு ஒரு செய்தி அனுப்புங்கள்",
      nameLabel: "உங்கள் பெயர்",
      namePlaceholder: "உங்களை எப்படிக் குறிப்பிடலாம்?",
      emailFieldLabel: "மின்னஞ்சல் முகவரி",
      emailPlaceholder: "you@example.com",
      subjectLabel: "தொடர்புகொள்வதன் காரணம்",
      subjectOptions: ["பொதுவான விசாரணை", "கூட்டாண்மை", "எங்கள் திட்டங்கள்", "தன்னார்வம்", "வேறு விடயம்"],
      messageLabel: "உங்கள் செய்தி",
      messagePlaceholder: "உங்கள் எண்ணத்தைப் பற்றி கொஞ்சம் கூறுங்கள்...",
      send: "செய்தியை அனுப்புங்கள்",
      formNote: "இது ஒரு முன்னோட்டப் படிவம். செய்திகளைப் பெறுவதற்கு முன் அதிகாரப்பூர்வ மின்னஞ்சல் அல்லது படிவச் சேவையை இணைக்கவும்.",
    },
  },
  ko: {
    nav: {
      home: "홈",
      about: "소개",
      koica: "KOICA",
      projects: "프로젝트",
      dissemination: "지식 보급",
      gallery: "갤러리",
      contact: "문의하기",
    },
    common: {
      siteTitle: "AKOFE 스리랑카 | 함께 더 밝게 성장합니다",
      skipToContent: "본문으로 건너뛰기",
      language: "언어",
      mainNavigation: "주요 메뉴",
      menu: "메뉴 열기",
      close: "메뉴 닫기",
      getInvolved: "함께하기",
      learnMore: "자세히 보기",
      explore: "활동 살펴보기",
      viewProjects: "모든 프로젝트 보기",
      readStory: "우리 이야기 읽기",
      visit: "방문하기",
      email: "이메일 보내기",
      call: "전화하기",
      footerNote: "지역사회에 뿌리내리고 가능성과 함께 성장합니다.",
      footerDescription: "스리랑카 KOICA 동문회(AKOFE)는 한국국제협력단(KOICA)이 후원한 연수, 연구 및 학술 프로그램에 참여한 스리랑카 전문가들의 역동적인 네트워크입니다.",
      footerLine: "모든 지역사회가 함께 성장하는 미래.",
      footerExplore: "둘러보기",
      footerPartners: "파트너",
      footerFollow: "AKOFE 팔로우",
      rights: "© 2025 AKOFE 스리랑카. 모든 권리 보유.",
      backToTop: "맨 위로",
    },
    home: {
      eyebrow: "AKOFE – SRI LANKA",
      title: "함께라면",
      highlight: "더 밝게 성장할 수 있습니다.",
      lead: "스리랑카 KOICA 동문회(AKOFE)는 한국국제협력단(KOICA)이 후원한 연수, 연구 및 학술 프로그램에 참여한 스리랑카 전문가들의 역동적인 네트워크입니다.",
      primary: "활동 살펴보기",
      secondary: "우리는 누구인가요",
      scroll: "더 알아보기",
      photoNoteLineOne: "사람이 먼저.",
      photoNoteLineTwo: "함께 만드는 진전.",
      stampTop: "지역사회에",
      stampWord: "뿌리내리고",
      stampBottom: "함께 성장합니다",
      sectionAside: "더 나은 길을\n함께 만들어 갑니다",
      heroImageAlt: "야외에서 함께 활동하는 사람들",
      slidesLabel: "메인 비주얼",
      carouselDescription: "슬라이드쇼",
      slideDescription: "슬라이드",
      slideOf: "중",
      slideLabels: ["지역사회의 이야기", "함께하는 사람들", "성장의 터전", "함께 성장하기", "더 밝은 미래"],
      previousSlide: "이전 슬라이드",
      nextSlide: "다음 슬라이드",
      statOne: "활동 연수",
      statTwo: "회원",
      statThree: "프로젝트",
      introEyebrow: "AKOFE 소개",
      introTitle: "스리랑카 KOICA 동문회(AKOFE)",
      introBody: "AKOFE는 KOICA가 후원한 연수, 연구, 학술 프로그램에 참여한 스리랑카 전문가들의 자원봉사 네트워크입니다. 전문가 교류와 지역사회 및 개발 활동을 통해 동문 간 유대를 강화하고 스리랑카와 한국 간 지식 공유와 협력을 촉진합니다.",
      sdgTitle: "지속가능발전목표(SDGs)에 대한 기여",
      sdgNote: "AKOFE의 활동은 학습, 전문가 네트워크, 지역사회 활동, 국제 협력을 통해 다음 목표에 부합합니다.",
      sdgGoals: [
        ["04", "양질의 교육", "지식을 나누고 평생 학습을 지원합니다."],
        ["08", "양질의 일자리와 경제성장", "전문가를 연결하고 역량을 강화합니다."],
        ["09", "산업, 혁신과 사회기반시설", "전문성, 기술, 실용적인 아이디어를 공유합니다."],
        ["17", "목표를 위한 파트너십", "스리랑카와 한국 간 협력을 구축합니다."],
      ],
      workEyebrow: "중점 분야",
      workTitle: "작은 걸음, 오래가는 변화.",
      workBody: "배움부터 생계까지, 모든 활동은 지역의 우선순위에서 출발합니다.",
      projectTitle: "함께할 때 좋은 일이 자라납니다.",
      projectBody: "지역사회의 목소리로 만들고 파트너십으로 키워 가는 프로젝트를 만나 보세요.",
      closingTitle: "더 밝은 미래는 대화에서 시작됩니다.",
      closingBody: "아이디어나 질문이 있으신가요? 함께할 방법을 찾고 싶으신가요? 편하게 이야기해 주세요.",
      pillars: [
        ["01", "삶을 위한 배움", "모든 연령대가 지식과 기술, 자신감을 키울 수 있도록 기회를 엽니다."],
        ["02", "든든한 생계", "가족이 안정적이고 희망찬 미래를 만들어 가도록 지원합니다."],
        ["03", "함께 성장하는 지역사회", "모두가 소속감을 느끼도록 연결과 지역 활동을 키웁니다."],
      ],
    },
    about: {
      eyebrow: "우리의 이야기",
      title: "AKOFE",
      heroTagline: "900명 이상의 회원이 이끄는, 섬 전역으로 연결된",
      highlight: "",
      lead: "스리랑카 KOICA 동문회(AKOFE)는 한국국제협력단(KOICA)의 연수, 연구, 학술 프로그램에 참여한 스리랑카 전문가들을 연결하는 자발적 단체입니다.",
      imageAlt: "KOICA 동문들이 만나 생각을 나누는 모습",
      introTitle: "배움과 봉사로 이어지는 네트워크.",
      introBody: "1999년에 설립된 AKOFE는 한국 정부 장학금을 받아 한국에서 연수를 받은 고위 공무원과 전직 공직자를 연결합니다. 900명이 넘는 회원은 교육, 보건, 환경, 거버넌스 등 다양한 분야에서 세미나, 지역사회 개발 활동, 전문가 교류 행사를 통해 지식을 나눕니다.",
      missionLabel: "우리의 회원",
      missionTitle: "스리랑카와 한국의 우정을 강화합니다.",
      missionBody: "AKOFE는 KOICA 및 여러 파트너와 협력해 한국의 전문성, 기술, 경험을 현지 기관과 지역사회에 전하고 국가 발전과 도움이 필요한 사람들을 지원합니다.",
      valuesTitle: "배움을 실천으로 잇습니다.",
      values: [
        ["지식 교류", "세미나와 학습 프로그램에서 회원들이 전문성과 실질적인 아이디어를 나눕니다."],
        ["지역사회 개발", "회원 주도의 활동으로 지역의 우선 과제와 도움이 필요한 공동체에 경험과 역량을 보탭니다."],
        ["전문가 네트워크", "행사를 통해 여러 분야의 동문이 연결되고 협력의 기회를 만듭니다."],
        ["스리랑카–한국 협력", "AKOFE는 KOICA 및 파트너와 함께 한국의 전문성, 기술, 경험을 나눕니다."],
      ],
      presidentTitle: "회장 인사말.",
      executiveTitle: "임원진",
      presidentMessage: "AKOFE와 동문들의 활동을 소개하게 되어 기쁩니다. 회원들은 KOICA 프로그램에서 배운 내용을 각자의 분야에서 혁신과 봉사, 협력의 가치로 실천하고 있습니다. 변함없이 지원해 주시는 KOICA와 헌신적인 회원, 파트너 여러분께 감사드립니다. 함께 지식을 실천으로 옮겨 스리랑카의 발전과 양국의 우정에 기여하겠습니다.",
      presidentName: "로샨 세라싱헤",
      presidentRole: "스리랑카 KOICA 동문회 회장",
      closingTitle: "의미 있는 변화를 함께 만들어 보세요.",
      closingBody: "좋은 파트너십은 인사 한마디에서 시작됩니다. 중요한 이야기를 들려주세요.",
    },
    koica: {
      eyebrow: "함께 만드는 진전",
      title: "지속적인 변화를 위해",
      highlight: "함께합니다.",
      lead: "AKOFE와 KOICA는 스리랑카 지역사회를 위한 파트너십과 사람 중심의 실질적인 발전을 지향합니다.",
      imageAlt: "테이블에 둘러앉아 함께 일하는 파트너들",
      introTitle: "목적을 함께하는 파트너십.",
      introBody: "한국국제협력단(KOICA)은 지속 가능한 발전을 위해 전 세계에서 활동합니다. KOICA 페이지에서는 국제 협력의 정신과 지역사회가 더 많은 기회를 만들어 가도록 돕는 공동의 노력을 소개합니다.",
      noteTitle: "지역의 목소리, 공동의 목표.",
      noteBody: "지역의 지식이 중심이 될 때 국제 협력은 더욱 큰 힘을 발휘합니다. 의미 있는 파트너십을 만드는 아이디어와 관계, 함께하는 배움을 소중히 여깁니다.",
      focusTitle: "파트너십이 만드는 가능성.",
      focus: [
        ["01", "함께 배우기", "지역과 문화를 넘어 경험과 아이디어를 나눕니다."],
        ["02", "더 긴밀한 연결", "지역 단체와 국제 파트너가 나란히 일할 기회를 만듭니다."],
        ["03", "지속 가능한 발전", "장기적인 발전의 중심에 지역사회의 우선순위를 둡니다."],
      ],
      quote: "“사람들이 자신의 미래를 만들어 가는 파트너가 될 때 발전은 더 큰 힘을 얻습니다.”",
      quoteBy: "협력의 정신",
      closingTitle: "함께할 방법을 찾고 계신가요?",
      closingBody: "사람 중심의 발전을 위해 노력하는 단체와의 대화를 환영합니다.",
      overviewTitle: "스리랑카의 KOICA",
      overviewBody: "한국국제협력단(KOICA)은 지속 가능한 발전을 지원하기 위해 협력국과 함께합니다. 스리랑카에서 KOICA는 현지 기관 및 지역사회와 협력하며, CIAT 연수 프로그램을 통해 공공 부문 관계자들이 한국에서 지식과 역량을 키우도록 지원합니다.",
      officialLinksLabel: "KOICA 공식 자료",
      globalLinkLabel: "KOICA 글로벌 웹사이트",
      missionLinkLabel: "미션과 비전",
      officeLinkLabel: "KOICA 스리랑카 사무소 웹사이트",
      directorSectionTitle: "KOICA 국가사무소장의 메시지",
      directorMessage: "KOICA CIAT 연수 프로그램은 다양한 분야의 지식과 역량을 높이기 위해 협력국 공공 부문 관계자들을 한국으로 초청하는 한국의 대표적인 인적자원 개발 사업입니다. KOICA는 각자의 분야에서 국가 발전에 계속 기여하는 동문을 자랑스럽게 생각합니다. KOICA 동문 네트워크를 굳건히 이어 주시는 AKOFE에 진심으로 감사드립니다. 여러분의 헌신은 협력의 정신과 한국·스리랑카 간 오랜 우정을 더욱 깊게 합니다. 여러분은 두 나라 우정의 진정한 가교입니다. AKOFE의 지속적인 성공과 번영을 기원합니다.",
      directorName: "Lee YooLi",
      directorRole: "국가사무소장, KOICA 스리랑카 사무소",
      directorImageAlt: "KOICA 스리랑카 사무소장 Lee YooLi",
      videoTitle: "현장에서 만나는 KOICA",
      videoDescription: "KOICA의 협력과 연수 활동에 대해 영상으로 더 알아보세요.",
      videoFrameTitle: "KOICA 소개 영상",
    },
    projects: {
      eyebrow: "현장에서 만드는 변화",
      title: "지역사회에 힘을, 미래에 지속가능성을.",
      highlight: "",
      lead: "AKOFE는 한국에서 얻은 배움을 교육, 사회, 지속가능발전 분야의 맞춤형 활동으로 스리랑카 전역의 현지 실천으로 이어갑니다.",
      imageAlt: "워크숍에서 아이디어를 나누는 사람들",
      introTitle: "AKOFE 프로젝트 현장.",
      introBody: "연도, 지역, 지속가능발전목표별로 프로젝트를 살펴보고 상세 내용과 사진을 확인하세요.",
      projectsTitle: "다양한 활동을 소개합니다.",
      projects: [
        ["배움과 기술", "배우고 기술을 나누며 앞으로 나아갈 자신감을 키우는 기회를 만듭니다.", "교육"],
        ["지역사회 웰빙", "사람과 가족이 건강하게 성장하도록 돌봄과 연결, 지역의 활동을 지원합니다.", "웰빙"],
        ["지속 가능한 미래", "회복력 있는 생계와 건강한 환경을 위해 지역사회와 함께합니다.", "지속 가능성"],
        ["파트너십과 교류", "지역 단체와 파트너를 연결해 지식을 나누고 좋은 아이디어를 확산합니다.", "파트너십"],
      ],
      statusNote: "프로젝트 정보가 업데이트 중입니다. 현재 활동에 대해 궁금하시면 문의해 주세요.",
      closingTitle: "프로젝트 아이디어가 있으신가요?",
      closingBody: "지역사회를 아끼는 분들을 언제나 환영합니다.",
    },
    dissemination: {
      title: "지식 보급",
      lead: "AKOFE는 실습 교육, 강연, 기자재 기증 프로그램을 통해 스리랑카 전역의 학생, 교사, 전문가들과 실용적이고 혁신적인 기술을 나눕니다.",
      programsLabel: "프로그램",
      photosLabel: "행사 사진 하이라이트",
      topic: "강연 주제",
      person: "강연자",
      closingTitle: "프로그램을 개최하고 싶으신가요?",
      closingBody: "학교, 기관 또는 단체에서 AKOFE 지식 보급 프로그램을 열고 싶다면 연락해 주세요.",
    },
    gallery: {
      eyebrow: "순간과 발자취",
      title: "한 프레임에 담긴 천 마디 말.",
      highlight: "",
      lead: "움직이는 우리의 사명을 만나 보세요. 역량 강화 워크숍부터 풀뿌리 봉사 활동까지, 이 사진들은 스리랑카 전역에서 AKOFE가 이끄는 진짜 변화의 이야기를 담고 있습니다.",
      momentsLabel: "순간",
      note: "여기에 표시된 사진은 AKOFE가 기록한 프로젝트 활동에서 선정했습니다.",
      closingTitle: "나누고 싶은 순간이 있나요?",
      closingBody: "지역사회를 특별하게 만드는 사람들과 이야기를 함께 나누고 싶습니다.",
    },
    contact: {
      eyebrow: "이야기를 나눠요",
      title: "소통하기 위해 여기 있습니다.",
      highlight: "",
      lead: "문의나 협력 아이디어가 있으신가요? 스리랑카 코이카 펠로우 협회(AKOFE)에 연락해 주세요. 지속가능한 발전을 함께 이끌어 갈 방법을 논의하겠습니다.",
      introTitle: "여러분의 이야기를 기다립니다.",
      introBody: "AKOFE와 활동, 함께할 방법에 대해 궁금하시면 연락해 주세요. 알맞은 안내를 드리겠습니다.",
      addressLabel: "오시는 길",
      address: "스리랑카",
      emailLabel: "이메일",
      email: "공식 이메일 주소를 추가해 주세요",
      phoneLabel: "전화",
      phone: "공식 전화번호를 추가해 주세요",
      formTitle: "메시지 보내기",
      nameLabel: "이름",
      namePlaceholder: "어떻게 불러 드릴까요?",
      emailFieldLabel: "이메일 주소",
      emailPlaceholder: "you@example.com",
      subjectLabel: "문의 내용",
      subjectOptions: ["일반 문의", "파트너십", "프로젝트", "자원봉사", "기타"],
      messageLabel: "메시지",
      messagePlaceholder: "어떤 생각을 하고 계신지 들려주세요...",
      send: "메시지 보내기",
      formNote: "이 양식은 미리보기이며 아직 연결되지 않았습니다. 메시지를 받으려면 공식 이메일 또는 폼 서비스를 설정해 주세요.",
    },
  },
} as const;
